### ISSUE TITLE
Discount 

### ISSUE THREAD

**Issue by datdo06** [WailanTirajoh/Laravel-Hotel#23]
You can create and use discount codes when booking (Manage discount codes)?

**Comment by WailanTirajoh** [comment]
You can create 1 model for "Discount" and then create a pivot table (discount_transaction) between transaction and discount, so 1 discount can be applied at multiple transactions, and then 1 transactions can have multiple discount. But you also should create some logic to handle threshold that multiple discount to be applied, otherwise if user can apply multiple discount and the value is larger then payment, then you have to pay the customer money XD. I can only share logic for now, since have no time for 2 ~ 3 week for this project development.

**Comment by WailanTirajoh** [comment]
Just to be noted, you need to save the **total price after discount** & **total price before discount** & **discount price** into transactions table also so you can easily track which transaction got discount, etc etc when come into the audit.

**Comment by datdo06** [comment]
thanks
